version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: standard
      - dependency-name: hallmark
      - dependency-name: "@types/node"
      - dependency-name: "@voxpelli/tsconfig"
      - dependency-name: typescript
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
